### ISSUE TITLE
Autocomplete do not work with the default theme

### ISSUE THREAD

**Issue by NerosTie** [NerosTie/emojione#3]
The autocomplete function of emojione do not work with the default theme of Shaarli.

It works very well with https://github.com/kalvn/Shaarli-Material, though.

**Comment by NerosTie** [comment]
Could be related to this error I have with the default theme: 
`autocomplete.js:6 Uncaught TypeError: $(...).textcomplete is not a function`

**Comment by kalvn** [comment]
It's because of this line in the file `editlink.html` of the official Shaarli repo:

``` html
<script src="inc/awesomplete-multiple-tags.js#"></script>
```

This script actually redefines the javascript variable `$` which completely removes the `textcomplete` function attached to it previously (it explains the error).

As it's a very bad practice to define such variable in the global namespace, I'll open an issue on Shaarli about that.

**Comment by NerosTie** [comment]
Fixed with https://github.com/shaarli/Shaarli/pull/550

Thanks! :smile:
